# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 21:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(choices=[(0, 'correctAnswer'), (1, 'wrongAnswer1'), (2, 'wrongAnswer2'), (3, 'wrongAnswer3')])),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
                ('ratingHygiene', models.FloatField()),
                ('ratingStaff', models.FloatField()),
                ('ratingFacilities', models.FloatField()),
                ('reviewLink', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('seq', models.IntegerField()),
                ('text', models.CharField(max_length=360)),
                ('desc', models.CharField(max_length=360)),
                ('correctAnswer', models.CharField(max_length=120)),
                ('wrongAnswer1', models.CharField(max_length=120)),
                ('wrongAnswer2', models.CharField(max_length=120)),
                ('wrongAnswer3', models.CharField(max_length=120)),
                ('correctAnswerUrl', models.URLField()),
                ('wrongAnswer1Url', models.URLField()),
                ('wrongAnswer2Url', models.URLField()),
                ('wrongAnswer3Url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('desc', models.CharField(max_length=360)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other'), ('Unspecified', "Don't want to disclose")], max_length=10)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(110)])),
                ('city', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='game.Subject'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='game.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='game.User'),
        ),
    ]
