# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20170414_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='location',
        ),
        migrations.AddField(
            model_name='hospital',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
    ]
